package es.ams.iomonad

import es.ams.basic.OperationsMacro
import es.ams.macrosamples.domain.Rectangle
import io.getquill.{ActionReturning, Delete, Insert, Update}
import io.getquill.context.Context

import scala.language.experimental.macros

trait QueriesIOMonad {

  this: Context[_, _] =>

  def insertMacro[T](entity: T): Quoted[Insert[T]] = macro OperationsMacro.insert[T]

  def insertAutoGenerated[T](entity: T): Quoted[ActionReturning[T, Int]] = macro OperationsMacro.insertAutoGenerated[T]

  def update[T](entity: T): Quoted[Update[T]] = macro OperationsMacro.update[T]

  def delete[T](entity: T): Quoted[Delete[T]] = macro OperationsMacro.delete[T]

  def selectAllRectangle() = quote {
    query[Rectangle]
  }

}
